<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework></PropertyGroup>
  <ItemGroup><ProjectReference Include="../theme-measure-lib/theme-measure-lib.fsproj" /></ItemGroup>
  <ItemGroup><Compile Include="Program.fs" /></ItemGroup>
</Project>
