<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>visual-engineering</AssemblyName>
    <RootNamespace>VisualEngineering.Cli</RootNamespace>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <PublishTrimmed>true</PublishTrimmed>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <TrimMode>partial</TrimMode>
    <DebugType>none</DebugType>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Options.fs" />
    <Compile Include="Help.fs" />
    <Compile Include="Parser.fs" />
    <Compile Include="Render.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VisualEngineering.Core\VisualEngineering.Core.fsproj" />
  </ItemGroup>

</Project>
